version: '3.8'
services:
  mongodb:
    image: mongo:4.4-bionic
    container_name: mongo
    hostname: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_ADMIN
      - MONGO_INITDB_ROOT_PASSWORD=$DB_ADMIN_PWD
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_INITDB_USERNAME=$DB_USER
      - MONGO_INITDB_PASSWORD=$DB_USER_PWD
    volumes:
      - ./addons/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - dbdata:/data/db
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata:
